Data
BB8-2020/EmpathicRobot pull request #23
Opened 2021-06-14 12:52 UTC by stormjoannes

This request contain the data branch, including data process files and data test files.

2021-06-14 13:04 UTC, stormjoannes commented
Check failed because of non existing docstring at the beginning of .py files.

2021-06-15 10:14 UTC, MariaDukmak commented on data/affectNet/affectNet_functions.py
> +def get_latest_index():
Deze functie kan verkleint worden. Probeer ook aan je variabelen namen te denken. :))

2021-06-15 10:16 UTC, MariaDukmak commented on data/affectNet/affectNet_functions.py
> +def get_latest_index() -> int:
Deze functie kan kleiner :) denk aan een bestande functie gebruiken van numpy 😉 Denk aan je variabelen name 
Mooie typehinting. :)

2021-06-15 10:17 UTC, MariaDukmak commented on data/affectNet/affectNet_functions.py
> +    # Because of the heavy weight of this dataset we decided to max it at 28 images.
Just 28 images 😮

2021-06-15 10:18 UTC, MariaDukmak commented on data/affectNet/affectNet_functions.py
> +        X: np.ndarray
Zijn de x en y al genormaliseerd hier?

2021-06-15 10:24 UTC, MariaDukmak commented on data/general_defenitions.py
> +        if datagen is not None:
deze kan ook kleiner :0 En de plt.xticks en y kunnen weg vgm :)

2021-06-15 10:25 UTC, MariaDukmak commented on data/general_defenitions.py
> +            Wanted filename for pkl file
compressed pickel? :)

2021-06-15 10:28 UTC, MariaDukmak commented on tests/test_data_affectnet.py
> +from data.affectNet.affectNet_functions import preprocess_data, clean_data_and_normalize, get_latest_index, \
doe het in een regel de import

2021-06-15 10:32 UTC, MariaDukmak commented on tests/test_data_affectnet.py
> +def test_get_latest_index():
Check de feedback van de functie

2021-06-15 10:37 UTC, MariaDukmak commented on tests/test_data_ferplus.py
> +    data = pd.read_csv('tests/dataprocessing/fer2013_sample.csv')
Gebruik @pytest.fixture hiervoor!

2021-06-15 10:37 UTC, MariaDukmak commented on tests/test_data_general.py
> +data = pd.read_csv('tests/dataprocessing/fer2013_sample.csv')
Gebruik @pytest.fixture hiervoor!

2021-06-15 10:43 UTC, MariaDukmak commented on tests/test_data_general.py
> +    expected = (10.0, 7.0)
wat is dit precies?

2021-06-15 10:45 UTC, MariaDukmak requested changes
Probeer de feedback te verwerken!

2021-06-15 11:53 UTC, MariaDukmak approved these changes

2021-06-15 11:54 UTC, merged